// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkR8v6sKqW78wmKn9AEMqbibzLM5CHmm4',
    appId: '1:353235625395:web:7ccae81df379c6eee057c6',
    messagingSenderId: '353235625395',
    databaseURL: "https://impara-gurmu-default-rtdb.firebaseio.com/",
    projectId: 'impara-gurmu',
    authDomain: 'impara-gurmu.firebaseapp.com',
    storageBucket: 'impara-gurmu.firebasestorage.app',
    measurementId: 'G-Z55T25MHL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRR14dJPMvF9yHPyVxrmz4zbGKjdTL40A',
    appId: '1:353235625395:android:50537deff6288f80e057c6',
    messagingSenderId: '353235625395',
    databaseURL: "https://impara-gurmu-default-rtdb.firebaseio.com/",
    projectId: 'impara-gurmu',
    storageBucket: 'impara-gurmu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd1lbIUAwxCKAqhCgB22v5EqOFRoOEVfY',
    appId: '1:353235625395:ios:1a236e4fda29ddb0e057c6',
    messagingSenderId: '353235625395',
    databaseURL: "https://impara-gurmu-default-rtdb.firebaseio.com/",
    projectId: 'impara-gurmu',
    storageBucket: 'impara-gurmu.firebasestorage.app',
    iosBundleId: 'com.example.imparaGurbani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd1lbIUAwxCKAqhCgB22v5EqOFRoOEVfY',
    appId: '1:353235625395:ios:1a236e4fda29ddb0e057c6',
    messagingSenderId: '353235625395',
    databaseURL: "https://impara-gurmu-default-rtdb.firebaseio.com/",
    projectId: 'impara-gurmu',
    storageBucket: 'impara-gurmu.firebasestorage.app',
    iosBundleId: 'com.example.imparaGurbani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkR8v6sKqW78wmKn9AEMqbibzLM5CHmm4',
    appId: '1:353235625395:web:fa3f9fed0ec01f76e057c6',
    messagingSenderId: '353235625395',
    projectId: 'impara-gurmu',
    databaseURL: "https://impara-gurmu-default-rtdb.firebaseio.com/",
    authDomain: 'impara-gurmu.firebaseapp.com',
    storageBucket: 'impara-gurmu.firebasestorage.app',
    measurementId: 'G-G0N4Y5ZP6Y',
  );
}
