// List of Punjabi alphabet letters
final List<String> punjabiAlphabet = [
  "ੳ",
  "ਅ",
  "ੲ",
  "ਸ",
  "ਹ",
  "ਕ",
  "ਖ",
  "ਗ",
  "ਘ",
  "ਙ",
  "ਚ",
  "ਛ",
  "ਜ",
  "ਝ",
  "ਞ",
  "ਟ",
  "ਠ",
  "ਡ",
  "ਢ",
  "ਣ",
  "ਤ",
  "ਥ",
  "ਦ",
  "ਧ",
  "ਨ",
  "ਪ",
  "ਫ",
  "ਬ",
  "ਭ",
  "ਮ",
  "ਯ",
  "ਰ",
  "ਲ",
  "ਵ",
  "ੜ",
  "ਸ਼",
  "ਜ਼",
  "ਖ਼",
  "ਗ਼",
  "ਫ਼",
  "ਲ਼",
];
final List<String> punjabiPronunciations = [
  "Urha",
  "Èrha",
  "Irhi",
  "Sassaa",
  "Haha",
  "Kakkaa",
  "Khakkhaa",
  "Gaggaa",
  "Ghagghaa",
  "Nganga",
  "Chachaa",
  "Chhachhaa",
  "Jajjaa",
  "Jhajjhaa",
  "Gnagna",
  "Tènkaa",
  "ThaTThaa",
  "DaDDaa",
  "DdhaDdhaa",
  "nNanNa",
  "tattaa",
  "thatthaa",
  "daddaa",
  "dhaddhaa",
  "Nannaa",
  "Pappaa",
  "Faffaa",
  "Babbaa",
  "Bhabbhaa",
  "Mammaa",
  "Yayaa",
  "Rara",
  "Lallaa",
  "Vava",
  "RhaRha",
  "Shashaa",
  "Zazaa",
  "Khhakhhaa",
  "gagaa",
  "Fafaa",
  "Lalaa"
];

// Lista delle vocali
final List<Map<String, String>> segniVocali = [
  {"◌ਾ": "Kannaa"},
  {" ਿ": "Sihaari"},
  {"◌ੀ": "Bihaari"},
  {"◌ੁ": "ÒnkaRh"},
  {"◌ੂ": "DulenkaRh"},
  {"◌ੇ": "Lava(n)"},
  {"◌ੈ": "Dulavaa(n)"},
  {"◌ੋ": "HoRha"},
  {"◌ੌ": "KnòRha"},
];
final List<String> punjabiVowels = [
  "ਅ",
  "ਆ",
  "ਇ",
  "ਈ",
  "ਉ",
  "ਊ",
  "ਏ",
  "ਐ",
  "ਓ",
  "ਔ"
];
final List<String> punjabiVowelPronunciations = [
  "a",
  "aa",
  "i",
  "ii",
  "u",
  "uu",
  "e",
  "ai",
  "o",
  "au"
];

// Lista delle lettere iniziali
final List<String> MuharniBase = [
  "ਕ",
  "ਖ",
  "ਗ",
  "ਘ",
  "ਙ",
  "ਚ",
  "ਛ",
  "ਜ",
  "ਝ",
  "ਞ",
  "ਟ",
  "ਠ",
  "ਡ",
  "ਢ",
  "ਣ",
  "ਤ",
  "ਥ",
  "ਦ",
  "ਧ",
  "ਨ",
  "ਪ",
  "ਫ",
  "ਬ",
  "ਭ",
  "ਮ",
  "ਯ",
  "ਰ",
  "ਲ",
  "ਵ",
  "ੜ",
  "ਸ਼",
  "ਖ਼",
  "ਗ਼",
  "ਜ਼",
  "ਫ਼",
  "ਲ਼"
];
final Map<String, List<Map<String, String>>> muharniCombinations = {
  "ਕ": [
    {"ਕ": "ka"},
    {"ਕਾ": "kaa"},
    {"ਕਿ": "ki"},
    {"ਕੀ": "kee"},
    {"ਕੁ": "ku"},
    {"ਕੂ": "koo"},
    {"ਕੇ": "ke"},
    {"ਕੈ": "kai"},
    {"ਕੋ": "ko"},
    {"ਕੌ": "kau"},
    {"ਕੰ": "kan"},
    {"ਕਾਂ": "kaan"}
  ],
  "ਖ": [
    {"ਖ": "kha"},
    {"ਖਾ": "khaa"},
    {"ਖਿ": "khi"},
    {"ਖੀ": "khee"},
    {"ਖੁ": "khu"},
    {"ਖੂ": "khoo"},
    {"ਖੇ": "khe"},
    {"ਖੈ": "khai"},
    {"ਖੋ": "kho"},
    {"ਖੌ": "khau"},
    {"ਖੰ": "khan"},
    {"ਖਾਂ": "khaan"}
  ],
  "ਗ": [
    {"ਗ": "ga"},
    {"ਗਾ": "gaa"},
    {"ਗਿ": "gi"},
    {"ਗੀ": "gee"},
    {"ਗੁ": "gu"},
    {"ਗੂ": "goo"},
    {"ਗੇ": "ge"},
    {"ਗੈ": "gai"},
    {"ਗੋ": "go"},
    {"ਗੌ": "gau"},
    {"ਗੰ": "gan"},
    {"ਗਾਂ": "gaan"}
  ],
  "ਘ": [
    {"ਘ": "gha"},
    {"ਘਾ": "ghaa"},
    {"ਘਿ": "ghi"},
    {"ਘੀ": "ghee"},
    {"ਘੁ": "ghu"},
    {"ਘੂ": "ghoo"},
    {"ਘੇ": "ghe"},
    {"ਘੈ": "ghai"},
    {"ਘੋ": "gho"},
    {"ਘੌ": "ghau"},
    {"ਘੰ": "ghan"},
    {"ਘਾਂ": "ghaan"}
  ],
  "ਙ": [
    {"ਙ": "nga"},
    {"ਙਾ": "ngaa"},
    {"ਙਿ": "ngi"},
    {"ਙੀ": "ngee"},
    {"ਙੁ": "ngu"},
    {"ਙੂ": "ngoo"},
    {"ਙੇ": "nge"},
    {"ਙੈ": "ngai"},
    {"ਙੋ": "ngo"},
    {"ਙੌ": "ngau"},
    {"ਙੰ": "ngan"},
    {"ਙਾਂ": "ngaan"}
  ],
  "ਚ": [
    {"ਚ": "cha"},
    {"ਚਾ": "chaa"},
    {"ਚਿ": "chi"},
    {"ਚੀ": "chee"},
    {"ਚੁ": "chu"},
    {"ਚੂ": "chuu"},
    {"ਚੇ": "che"},
    {"ਚੈ": "chai"},
    {"ਚੋ": "cho"},
    {"ਚੌ": "chau"},
    {"ਚੰ": "chan"},
    {"ਚਾਂ": "chaan"}
  ],
  "ਛ": [
    {"ਛ": "chha"},
    {"ਛਾ": "chhaa"},
    {"ਛਿ": "chhi"},
    {"ਛੀ": "chhee"},
    {"ਛੁ": "chhu"},
    {"ਛੂ": "chhoo"},
    {"ਛੇ": "chhe"},
    {"ਛੈ": "chhai"},
    {"ਛੋ": "cho"},
    {"ਛੌ": "chau"},
    {"ਛੰ": "chan"},
    {"ਛਾਂ": "chhaan"}
  ],
  "ਜ": [
    {"ਜ": "ja"},
    {"ਜਾ": "jaa"},
    {"ਜਿ": "ji"},
    {"ਜੀ": "jee"},
    {"ਜੁ": "ju"},
    {"ਜੂ": "joo"},
    {"ਜੇ": "je"},
    {"ਜੈ": "jai"},
    {"ਜੋ": "jo"},
    {"ਜੌ": "jau"},
    {"ਜੰ": "jan"},
    {"ਜਾਂ": "jaan"}
  ],
  "ਝ": [
    {"ਝ": "jha"},
    {"ਝਾ": "jhaa"},
    {"ਝਿ": "jhi"},
    {"ਝੀ": "jhee"},
    {"ਝੁ": "jhu"},
    {"ਝੂ": "jhoo"},
    {"ਝੇ": "jhe"},
    {"ਝੈ": "jhai"},
    {"ਝੋ": "jho"},
    {"ਝੌ": "jhau"},
    {"ਝੰ": "jhan"},
    {"ਝਾਂ": "jhaan"}
  ],
  "ਞ": [
    {"ਞ": "nya"},
    {"ਞਾ": "nyaa"},
    {"ਞਿ": "nyi"},
    {"ਞੀ": "nyee"},
    {"ਞੁ": "nyu"},
    {"ਞੂ": "nyoo"},
    {"ਞੇ": "nye"},
    {"ਞੈ": "nyai"},
    {"ਞੋ": "nyo"},
    {"ਞੌ": "nyau"},
    {"ਞੰ": "nyan"},
    {"ਞਾਂ": "nyaan"}
  ],
  "ਟ": [
    {"ਟ": "tta"},
    {"ਟਾ": "ttaa"},
    {"ਟਿ": "tti"},
    {"ਟੀ": "ttee"},
    {"ਟੁ": "ttu"},
    {"ਟੂ": "ttoo"},
    {"ਟੇ": "tte"},
    {"ਟੈ": "ttai"},
    {"ਟੋ": "tto"},
    {"ਟੌ": "ttau"},
    {"ਟੰ": "ttan"},
    {"ਟਾਂ": "ttaan"}
  ],
  "ਠ": [
    {"ਠ": "ttha"},
    {"ਠਾ": "tthaa"},
    {"ਠਿ": "tthi"},
    {"ਠੀ": "tthee"},
    {"ਠੁ": "tthu"},
    {"ਠੂ": "tthoo"},
    {"ਠੇ": "tthe"},
    {"ਠੈ": "tthai"},
    {"ਠੋ": "ttho"},
    {"ਠੌ": "tthau"},
    {"ਠੰ": "tthan"},
    {"ਠਾਂ": "tthaan"}
  ],
  "ਡ": [
    {"ਡ": "dda"},
    {"ਡਾ": "ddaa"},
    {"ਡਿ": "ddi"},
    {"ਡੀ": "ddii"},
    {"ਡੁ": "ddu"},
    {"ਡੂ": "ddoo"},
    {"ਡੇ": "dde"},
    {"ਡੈ": "ddai"},
    {"ਡੋ": "ddo"},
    {"ਡੌ": "ddau"},
    {"ਡੰ": "ddan"},
    {"ਡਾਂ": "ddaan"}
  ],
  "ਢ": [
    {"ਢ": "ddha"},
    {"ਢਾ": "ddhaa"},
    {"ਢਿ": "ddhi"},
    {"ਢੀ": "ddhee"},
    {"ਢੁ": "ddhu"},
    {"ਢੂ": "ddhoo"},
    {"ਢੇ": "ddhe"},
    {"ਢੈ": "ddhai"},
    {"ਢੋ": "ddho"},
    {"ਢੌ": "ddhau"},
    {"ਢੰ": "ddhan"},
    {"ਢਾਂ": "ddhaan"}
  ],
  "ਣ": [
    {"ਣ": "naa"},
    {"ਣਾ": "naaa"},
    {"ਣਿ": "nii"},
    {"ਣੀ": "nee"},
    {"ਣੁ": "nuu"},
    {"ਣੂ": "noo"},
    {"ਣੇ": "ne"},
    {"ਣੈ": "nai"},
    {"ਣੋ": "no"},
    {"ਣੌ": "nau"},
    {"ਣੰ": "nan"},
    {"ਣਾਂ": "naan"}
  ],
  "ਤ": [
    {"ਤ": "ta"},
    {"ਤਾ": "taa"},
    {"ਤਿ": "ti"},
    {"ਤੀ": "tee"},
    {"ਤੁ": "tu"},
    {"ਤੂ": "too"},
    {"ਤੇ": "te"},
    {"ਤੈ": "tai"},
    {"ਤੋ": "to"},
    {"ਤੌ": "tau"},
    {"ਤੰ": "tan"},
    {"ਤਾਂ": "taan"}
  ],
  "ਥ": [
    {"ਥ": "tha"},
    {"ਥਾ": "thaa"},
    {"ਥਿ": "thi"},
    {"ਥੀ": "thee"},
    {"ਥੁ": "thu"},
    {"ਥੂ": "thoo"},
    {"ਥੇ": "the"},
    {"ਥੈ": "thai"},
    {"ਥੋ": "tho"},
    {"ਥੌ": "thau"},
    {"ਥੰ": "than"},
    {"ਥਾਂ": "thaan"}
  ],
  "ਦ": [
    {"ਦ": "da"},
    {"ਦਾ": "daa"},
    {"ਦਿ": "di"},
    {"ਦੀ": "dee"},
    {"ਦੁ": "du"},
    {"ਦੂ": "doo"},
    {"ਦੇ": "de"},
    {"ਦੈ": "dai"},
    {"ਦੋ": "do"},
    {"ਦੌ": "dau"},
    {"ਦੰ": "dan"},
    {"ਦਾਂ": "daan"}
  ],
  "ਧ": [
    {"ਧ": "dha"},
    {"ਧਾ": "dhaa"},
    {"ਧਿ": "dhi"},
    {"ਧੀ": "dhee"},
    {"ਧੁ": "dhu"},
    {"ਧੂ": "dhoo"},
    {"ਧੇ": "dhe"},
    {"ਧੈ": "dhai"},
    {"ਧੋ": "dho"},
    {"ਧੌ": "dhau"},
    {"ਧੰ": "dhan"},
    {"ਧਾਂ": "dhaan"}
  ],
  "ਨ": [
    {"ਨ": "na"},
    {"ਨਾ": "naa"},
    {"ਨਿ": "ni"},
    {"ਨੀ": "nee"},
    {"ਨੁ": "nu"},
    {"ਨੂ": "noo"},
    {"ਨੇ": "ne"},
    {"ਨੈ": "nai"},
    {"ਨੋ": "no"},
    {"ਨੌ": "nau"},
    {"ਨੰ": "nan"},
    {"ਨਾਂ": "naan"}
  ],
  "ਪ": [
    {"ਪ": "pa"},
    {"ਪਾ": "paa"},
    {"ਪਿ": "pi"},
    {"ਪੀ": "pee"},
    {"ਪੁ": "pu"},
    {"ਪੂ": "poo"},
    {"ਪੇ": "pe"},
    {"ਪੈ": "pai"},
    {"ਪੋ": "po"},
    {"ਪੌ": "pau"},
    {"ਪੰ": "pan"},
    {"ਪਾਂ": "paan"}
  ],
  "ਫ": [
    {"ਫ": "pha"},
    {"ਫਾ": "phaa"},
    {"ਫਿ": "phi"},
    {"ਫੀ": "phee"},
    {"ਫੁ": "phu"},
    {"ਫੂ": "phoo"},
    {"ਫੇ": "phe"},
    {"ਫੈ": "phai"},
    {"ਫੋ": "pho"},
    {"ਫੌ": "phau"},
    {"ਫੰ": "phan"},
    {"ਫਾਂ": "phaan"}
  ],
  "ਬ": [
    {"ਬ": "ba"},
    {"ਬਾ": "baa"},
    {"ਬਿ": "bi"},
    {"ਬੀ": "bee"},
    {"ਬੁ": "bu"},
    {"ਬੂ": "boo"},
    {"ਬੇ": "be"},
    {"ਬੈ": "bai"},
    {"ਬੋ": "bo"},
    {"ਬੌ": "bau"},
    {"ਬੰ": "ban"},
    {"ਬਾਂ": "baan"}
  ],
  "ਭ": [
    {"ਭ": "bha"},
    {"ਭਾ": "bhaa"},
    {"ਭਿ": "bhi"},
    {"ਭੀ": "bhee"},
    {"ਭੁ": "bhu"},
    {"ਭੂ": "bhoo"},
    {"ਭੇ": "bhe"},
    {"ਭੈ": "bhai"},
    {"ਭੋ": "bho"},
    {"ਭੌ": "bhau"},
    {"ਭੰ": "bhan"},
    {"ਭਾਂ": "bhaan"}
  ],
  "ਮ": [
    {"ਮ": "ma"},
    {"ਮਾ": "maa"},
    {"ਮਿ": "mi"},
    {"ਮੀ": "mee"},
    {"ਮੁ": "mu"},
    {"ਮੂ": "moo"},
    {"ਮੇ": "me"},
    {"ਮੈ": "mai"},
    {"ਮੋ": "mo"},
    {"ਮੌ": "mau"},
    {"ਮੰ": "man"},
    {"ਮਾਂ": "maan"}
  ],
  "ਯ": [
    {"ਯ": "ya"},
    {"ਯਾ": "yaa"},
    {"ਯਿ": "yi"},
    {"ਯੀ": "yee"},
    {"ਯੁ": "yu"},
    {"ਯੂ": "yoo"},
    {"ਏ": "e"},
    {"ਐ": "ai"},
    {"ਓ": "o"},
    {"ਔ": "au"},
    {"ਅੰ": "an"},
    {"ਅਂ": "ang"}
  ],
  "ਰ": [
    {"ਰ": "ra"},
    {"ਰਾ": "raa"},
    {"ਰਿ": "ri"},
    {"ਰੀ": "ree"},
    {"ਰੁ": "ru"},
    {"ਰੂ": "roo"},
    {"ਰੇ": "re"},
    {"ਰੈ": "rai"},
    {"ਰੋ": "ro"},
    {"ਰੌ": "rau"},
    {"ਰੰ": "ran"},
    {"ਰਾਂ": "raan"}
  ],
  "ਲ": [
    {"ਲ": "la"},
    {"ਲਾ": "laa"},
    {"ਲਿ": "li"},
    {"ਲੀ": "lee"},
    {"ਲੁ": "lu"},
    {"ਲੂ": "loo"},
    {"ਲੇ": "le"},
    {"ਲੈ": "lai"},
    {"ਲੋ": "lo"},
    {"ਲੌ": "lau"},
    {"ਲੰ": "lan"},
    {"ਲਾਂ": "laan"}
  ],
  "ਵ": [
    {"ਵ": "va"},
    {"ਵਾ": "vaa"},
    {"ਵਿ": "vi"},
    {"ਵੀ": "vee"},
    {"ਵੁ": "vu"},
    {"ਵੂ": "voo"},
    {"ਵੇ": "ve"},
    {"ਵੈ": "vai"},
    {"ਵੋ": "vo"},
    {"ਵੌ": "vau"},
    {"ਵੰ": "van"},
    {"ਵਾਂ": "vaan"}
  ],
  "ੜ": [
    {"ੜ": "rra"},
    {"ੜਾ": "rraa"},
    {"ੜਿ": "rri"},
    {"ੜੀ": "rree"},
    {"ੜੁ": "rru"},
    {"ੜੂ": "rruu"},
    {"ੜੇ": "rre"},
    {"ੜੈ": "rrai"},
    {"ੜੋ": "rro"},
    {"ੜੌ": "rrau"},
    {"ੜੰ": "rran"},
    {"ੜਾਂ": "rran"}
  ],
  "ਸ਼": [
    {"ਸ਼": "sha"},
    {"ਸ਼ਾ": "shaa"},
    {"ਸ਼ਿ": "shi"},
    {"ਸ਼ੀ": "shee"},
    {"ਸ਼ੁ": "shu"},
    {"ਸ਼ੂ": "shoo"},
    {"ਸ਼ੇ": "she"},
    {"ਸ਼ੈ": "shai"},
    {"ਸ਼ੋ": "sho"},
    {"ਸ਼ੌ": "shau"},
    {"ਸ਼ੰ": "shan"},
    {"ਸ਼ਾਂ": "shaan"}
  ],
  "ਖ਼": [
    {"ਖ਼": "kha"},
    {"ਖ਼ਾ": "khaa"},
    {"ਖ਼ਿ": "khi"},
    {"ਖ਼ੀ": "khee"},
    {"ਖ਼ੁ": "khu"},
    {"ਖ਼ੂ": "khoo"},
    {"ਖ਼ੇ": "khe"},
    {"ਖ਼ੈ": "khai"},
    {"ਖ਼ੋ": "kho"},
    {"ਖ਼ੌ": "khau"},
    {"ਖ਼ੰ": "khan"},
    {"ਖ਼ਾਂ": "khaan"}
  ],
  "ਗ਼": [
    {"ਗ਼": "gha"},
    {"ਗ਼ਾ": "ghaa"},
    {"ਗ਼ਿ": "ghi"},
    {"ਗ਼ੀ": "ghee"},
    {"ਗ਼ੁ": "ghu"},
    {"ਗ਼ੂ": "ghoo"},
    {"ਗ਼ੇ": "ghe"},
    {"ਗ਼ੈ": "ghai"},
    {"ਗ਼ੋ": "gho"},
    {"ਗ਼ੌ": "ghau"},
    {"ਗ਼ੰ": "ghan"},
    {"ਗ਼ਾਂ": "ghaan"}
  ],
  "ਜ਼": [
    {"ਜ਼": "za"},
    {"ਜ਼ਾ": "zaa"},
    {"ਜ਼ਿ": "zi"},
    {"ਜ਼ੀ": "zee"},
    {"ਜ਼ੁ": "zu"},
    {"ਜ਼ੂ": "zoo"},
    {"ਜ਼ੇ": "ze"},
    {"ਜ਼ੈ": "zai"},
    {"ਜ਼ੋ": "zo"},
    {"ਜ਼ੌ": "zau"},
    {"ਜ਼ੰ": "zan"},
    {"ਜ਼ਾ": "zaan"}
  ],
  "ਫ਼": [
    {"ਫ਼": "fa"},
    {"ਫ਼ਾ": "faa"},
    {"ਫ਼ਿ": "fi"},
    {"ਫ਼ੀ": "fee"},
    {"ਫ਼ੁ": "fu"},
    {"ਫ਼ੂ": "foo"},
    {"ਫ਼ੇ": "fe"},
    {"ਫ਼ੈ": "fai"},
    {"ਫ਼ੋ": "fo"},
    {"ਫ਼ੌ": "fau"},
    {"ਫ਼ੰ": "fan"},
    {"ਫ਼ਾਂ": "faan"}
  ],
  "ਲ਼": [
    {"ਲ਼": "lla"},
    {"ਲ਼ਾ": "llaa"},
    {"ਲ਼ਿ": "lli"},
    {"ਲ਼ੀ": "llee"},
    {"ਲ਼ੁ": "llu"},
    {"ਲ਼ੂ": "lloo"},
    {"ਲ਼ੇ": "lle"},
    {"ਲ਼ੈ": "llai"},
    {"ਲ਼ੋ": "llo"},
    {"ਲ਼ੌ": "llau"},
    {"ਲ਼ੰ": "llan"},
    {"ਲ਼ਾਂ": "llaan"}
  ],
};

final List<String> AdhakWords = [
  'ਬਚਿੱਤਰ',
  'ਮੱਤ',
  'ਮਿੱਤਰ',
  'ਮਿੱਤਰਤਾ',
  'ਲੱਕ',
  'ਅੱਖ',
  'ਅੱਖਰ',
  'ਅੱਧ',
  'ਸੱਜਣ',
  'ਸੱਟ',
  'ਸੱਤ',
  'ਸਪੁੱਤਰ',
  'ਸਰਬੱਤ',
  'ਸੁਣਖਾ',
  'ਸੁਲੱਖਣੀ',
  'ਗੜਗੱਜ',
  'ਘੱਟ',
  'ਚੱਕਰ',
  'ਜਗ',
  'ਟਰੱਕ ',
  'ਨਛੱਤਰ',
  'ਪੱਥਰ',
  'ਪਵਿੱਤਰ',
  'ਪੁੱਤਰ',
];
final List<String> AdhakPronunciations = [
  'Bacchitar',
  'Matt',
  'Mitter',
  'Mitterta',
  'Lakk',
  'Akh',
  'Akhar',
  'Addh',
  'Sajan',
  'Satt',
  'Satt',
  'Suputtar',
  'Sarbatt',
  'Sunakha',
  'Sulakhani',
  'Gaddgaj',
  'Ghat',
  'Chakkar',
  'Jag',
  'Truck',
  'Nachhattar',
  'Pathar',
  'Pavittar',
  'Putar',
];

final List<String> BindiWords = [
  "ਛਿਆਨਵੇਂ",
  "ਜਹਾਂਗੀਰ",
  "ਡਾਂਗ",
  "ਡਾਵਾਂ ਡੋਲ",
  "ਨਾਂਦੇੜ",
  "ਨੀਂਦ",
  "ਪਰਸੋਂ",
  "ਪਰਛਾਵਾਂ",
  "ਪੀਂਘ",
  "ਬਾਂਸ",
  "ਬਾਹ",
  "ਬਾਂਦਰ",
  "ਮਹਾਬਲੀ",
  "ਮਾਵਾਂ",
  "ਮੀਹ",
  "ਲਾਂਗਰੀ",
  "ਵਟਾਂਦਰਾ",
  "ਉਗਲ",
  "ਇਕਾਂਤ",
  "ਇੰਗਲੈਂਡ",
  "ਸੰਗਰਾਂਦ",
  "ਸਾਈ",
  "ਕਿਤਾਬਾਂ",
  "ਛਲਾਂਗ",
];
final List<String> BindiPronunciations = [
  "Chhianven",
  "Jahangir",
  "Dang",
  "Dawan Dol",
  "Nandera",
  "Neend",
  "Parson",
  "Parchhawan",
  "Peengh",
  "Baans",
  "Baah",
  "Baandar",
  "Mahabali",
  "Mawan",
  "Meeh",
  "Langri",
  "Vatandra",
  "Ugal",
  "Ikant",
  "England",
  "Sangrand",
  "Sai",
  "Kitaban",
  "Chhalang",
];

final List<String> TippiWords = [
  "ਖੰਭ",
  "ਚੰਦ",
  "ਜੰਗਲ",
  "ਜੁਗਨੂੰ",
  "ਠੰਢ",
  "ਤਲਵੰਡੀ",
  "ਥੰਮ",
  "ਨਿਰੰਕਾਰ",
  "ਬਸੰਤ",
  "ਭਗਵੰਤ",
  "ਭੁਜੰਗੀ",
  "ਮੈਨੂੰ",
  "ਰੰਕ",
  "ਰੰਗ",
  "ਲੰਗਰ",
  "ਅੰਗੂਰ",
  "ਸੰਸਾ",
  "ਸਤਸੰਗ",
  "ਸੰਦੂਕ",
  "ਸਮੁੰਦਰ",
  "ਸੁੰਦਰ",
  "ਹਰਿਬੰਸ",
  "ਹੇਮਕੁੰਟ",
  "ਕੁਲਵੰਤ",
];
final List<String> TippiPronunciations = [
  "Khambh",
  "Chand",
  "Jangal",
  "Jugnu",
  "Thand",
  "Talwandi",
  "Thamm",
  "Nirankar",
  "Basant",
  "Bhagwant",
  "Bhujangi",
  "Mainu",
  "Rank",
  "Rang",
  "Langar",
  "Angoor",
  "Sansa",
  "Satsang",
  "Sandook",
  "Samundar",
  "Sundar",
  "Haribans",
  "Hemkunt",
  "Kulwant",
];

final List<String> MuktaWords = [
  "ਹਰਮਨ",
  "ਹਲਚਲ",
  "ਕਰਮ",
  "ਗੜਬੜ",
  "ਘਰ",
  "ਚਲ",
  "ਜਗਤ",
  "ਜਨ",
  "ਜਲਥਲ",
  "ਤਪ",
  "ਦਰਸਨ",
  "ਧਰਮ",
  "ਨਫਰਤ",
  "ਪਰਬਤ",
  "ਬਲ",
  "ਭਗਤ",
  "ਭਰ",
  "ਰਸ",
  "ਰਤਨ",
  "ਅਮਰ",
  "ਸਬਰ",
  "ਸ਼ਰਮ",
  "ਹਰ",
  "ਹਰਕਤ",
];
final List<String> MuktaPronunciations = [
  "Harman",
  "Halchal",
  "Karam",
  "Garbhar",
  "Ghar",
  "Chal",
  "Jagat",
  "Jan",
  "Jalthal",
  "Tap",
  "Darsan",
  "Dharm",
  "Nafrat",
  "Parbat",
  "Bal",
  "Bhagat",
  "Bhar",
  "Ras",
  "Ratan",
  "Amar",
  "Sabar",
  "Sharm",
  "Har",
  "Harkat",
];

final List<String> KannaWords = [
  "ਹਾਰ",
  "ਕਮਰਾ",
  "ਕਰਾਮਾਤ",
  "ਕਾਦਰ",
  "ਘਾਲ",
  "ਚਾਲ",
  "ਜਾਨ",
  "ਟਕਸਾਲ",
  "ਤਾਪ",
  "ਦਸਤਾਰ",
  "ਦਰਬਾਰ ",
  "ਪਰਸ਼ਾਦ",
  "ਬਾਬਲ",
  "ਬਾਬਾ",
  "ਬਾਲ",
  "ਭਗਤਾ",
  "ਭਗਵਾਨ",
  "ਭਾਰ",
  "ਯਾਦਗਾਰ",
  "ਰਾਸ",
  "ਅਕਾਲ",
  "ਅਰਾਮ",
  "ਅਵਤਾਰ",
  "ਆਸਣ",
];
final List<String> KannaPronunciations = [
  "Haar",
  "Kamra",
  "Karamat",
  "Kadar",
  "Ghaal",
  "Chaal",
  "Jaan",
  "Taksal",
  "Taap",
  "Dastaar",
  "Darbar",
  "Parshad",
  "Babal",
  "Baba",
  "Bal",
  "Bhagta",
  "Bhagwan",
  "Bhaar",
  "Yaadgar",
  "Raas",
  "Akaal",
  "Araam",
  "Avtar",
  "Aasan",
];

final List<String> SihariWords = [
  "ਕਵਿਤਾ",
  "ਕਿਆ",
  "ਕਿਰਨ",
  "ਖਿਆਲ",
  "ਗਹਿਣਾ",
  "ਗਿਆ",
  "ਗਿਆਨ",
  "ਜਿਸ",
  "ਜ਼ਿਕਰ",
  "ਟਹਲ",
  "ਦਿਨ",
  "ਦਿਲ",
  "ਪਿਆਰ",
  "ਫਿਕਰ",
  "ਫਿਰ",
  "ਫਿਰਨ",
  "ਮਹਿਲ",
  "ਮਿਲ",
  " ਹਿਰਨ",
  "ਅਗਿਆਨ",
  "ਇਹ",
  "ਇਕ ",
  "ਸ਼ਹਿਰ",
  "ਕਹਿਣਾ",
];
final List<String> SihariPronunciations = [
  "Kavita",
  "Kiya",
  "Kiran",
  "Khiyaal",
  "Gahina",
  "Gia",
  "Gyaan",
  "Jis",
  "Zikar",
  "Tahal",
  "Din",
  "Dil",
  "Pyaar",
  "Fikar",
  "Phir",
  "Phiran",
  "Mahil",
  "Mil",
  "Hiran",
  "Agyan",
  "Ih",
  "Ik",
  "Sheher",
  "Kehna",
];

final List<String> BihariWords = [
  "ਕਾਰੀਗਰ",
  "ਕੀਰਤਨ",
  "ਗਰੀਬ",
  "ਜਸਬੀਰ",
  "ਜੀਤ",
  "ਜੀਭ",
  "ਝਰੀਟ",
  "ਠੀਕ",
  "ਨਕਲੀ",
  "ਪੀਰ",
  "ਬਲਬੀਰ",
  "ਬਾਜ਼ੀਗਰ",
  "ਬੀਰਬਲ",
  "ਮਸ਼ਕਰੀ",
  "ਮਲਾਈ",
  "ਮੀਤ",
  "ਰਜਾਈ",
  "ਰੀਤ",
  "ਲੀਕ",
  "ਵੀਰ",
  "ਅਸਲੀ",
  "ਅਮਰੀਕ",
  "ਅਮੀਰ",
  "ਸਰੀਰ",
];
final List<String> BihariPronunciations = [
  "Kaareegar",
  "Kirtan",
  "Gareeb",
  "Jasbeer",
  "Jit",
  "Jeev",
  "Jharit",
  "Theek",
  "Nakli",
  "Peer",
  "Balbeer",
  "Baazigar",
  "Birbal",
  "Mashkari",
  "Malai",
  "Meet",
  "Rajaai",
  "Reet",
  "Leak",
  "Veer",
  "Asli",
  "Amrik",
  "Ameer",
  "Shareer",
];

final List<String> OnkarhWords = [
  "ਸੁਰਮਾ ",
  "ਹਸਮੁਖ",
  "ਕੁਰਬਾਨੀ",
  "ਖੁਰਾਕ",
  "ਗੁਣ",
  "ਗੁਰ",
  "ਗੁਰਬਾਣੀ",
  "ਗੁਰਮੁਖ",
  "ਗੁਲਾਬ",
  "ਚੁਣ",
  "ਤੁਰਨਾ",
  "ਦੁਕਾਨ",
  "ਪੁਣ",
  "ਫੁਲਕਾਰੀ",
  "ਫੁਲਵਾੜੀ",
  "ਬੁਰਕੀ",
  "ਬੁਲ ਬੁਲ",
  "ਰਾਮਪੁਰ",
  "ਵਹੁਟੀ",
  "ਉਦਾਸ",
  "ਸਹੁ",
  "ਸੁਖ",
  "ਸੁਚ",
  "ਸੁਰ",
];
final List<String> OnkarhPronunciations = [
  "Surma ",
  "Hasmukh",
  "Qurbani",
  "Khuraak",
  "Gun",
  "Gur",
  "Gurbani",
  "Gurmukh",
  "Gulab",
  "Chun",
  "Turna",
  "Dukaan",
  "Pun",
  "Phulkari",
  "Phulwaari",
  "Burki",
  "Bul Bul",
  "Rampur",
  "Vahuti",
  "Udaas",
  "Sahu",
  "Sukh",
  "Such",
  "Sur",
];

final List<String> DulenkarhWords = [
  "ਕਰਤੂਤ",
  "ਕਾਰਤੂਸ",
  "ਜਰੂਰ",
  "ਜੂਠ",
  "ਝੂਠ",
  "ਡਮਰੂ",
  "ਧੂਫ",
  "ਪੂਰਬ",
  "ਫਜੂਲ",
  "ਫੂਕ",
  "ਬਾਪੂ",
  "ਬੂਹਾ",
  "ਮਜਦੂਰ",
  "ਮਨਜ਼ੂਰ",
  "ਮਾਸੂਮ",
  "ਰੂਪ",
  "ਵਾਹਿਗੁਰੂ",
  "ਸਰਦੂਲ",
  "ਸਾਧੂ",
  "ਸੁਰਖਰੂ",
  "ਸੂਰਜ",
  "ਸੂਰਬੀਰ",
  "ਹਜੂਰ",
  "ਕਸੂਰ",
];
final List<String> DulenkarhPronunciations = [
  "Kartoot",
  "Kartus",
  "Zaroor",
  "Juth",
  "Jhooth",
  "Damroo",
  "Dhoof",
  "Poorab",
  "Fazool",
  "Phook",
  "Bapu",
  "Booha",
  "Mazdoor",
  "Manzoor",
  "Masoom",
  "Roop",
  "Waheguru",
  "Sardool",
  "Sadhoo",
  "Surkhro",
  "Suraj",
  "Soorbeer",
  "Hazoor",
  "Kasoor",
];

final List<String> LavaaWords = [
  "ਸੇਬ",
  "ਸੇਵਕ",
  "ਸੇਵਾ",
  "ਕੱਪੜੇ",
  "ਕਰੇਲੇ",
  "ਕਲੇਸ਼",
  "ਕੇਸਰ",
  "ਖੇਡ",
  "ਗੁਰਦੇਵ",
  "ਗੁਰਮੇਲ",
  "ਤੇਰੇ",
  "ਦਸਮੇਸ਼",
  "ਦਰਵੇਸ਼",
  "ਨਿਤਨੇਮ",
  "ਬਨੇਰੇ",
  "ਬੇਨਤੀ",
  "ਭੇਡ",
  "ਮੇਜ਼",
  "ਮੇਰੇ",
  "ਮੇਲ",
  "ਉਪਦੇਸ਼",
  "ਸ਼ਮਸ਼ੇਰ",
  "ਸਵੇਰੇ",
  "ਸੁਖਦੇਵ",
];
final List<String> LavaaPronunciations = [
  "Seb",
  "Sevak",
  "Seva",
  "Kapde",
  "Karele",
  "Klesh",
  "Kesar",
  "Khed",
  "Gurdev",
  "Gurmela",
  "Tere",
  "Dasmesh",
  "Darvesh",
  "Nitnem",
  "Banere",
  "Benti",
  "Bhed",
  "Mez",
  "Mere",
  "Mel",
  "Updesh",
  "Shamsher",
  "Savere",
  "Sukhdev",
];

final List<String> DulaavaWords = [
  "ਸੁਖਚੈਨ",
  "ਸੁਖੈਨ",
  "ਸ਼ੈਤਾਨ",
  "ਸੈਨਾਪਤੀ",
  "ਸੈਰ",
  "ਹੈਰਾਨ",
  "ਕਵਲਨੈਣ",
  "ਕੈਦ",
  "ਖੈਰ",
  "ਜਰਨੈਲ",
  "ਜੈਕਾਰਾ",
  "ਤੈਰ",
  "ਨਿਰਵੈਰ",
  "ਨੈਣ",
  "ਬੈਠ",
  "ਭੈਣ",
  "ਭੈਰਵ",
  "ਮਧੁਰਬੈਣ",
  "ਮੈਦਾਨ",
  "ਰੈਣ",
  "ਵੈਰਾਗ",
  "ਐਤਵਾਰ",
  "ਐਲਾਨ",
  "ਸਵੈਟਰ",
];
final List<String> DulaavaPronunciations = [
  "Sukhchain",
  "Sukhain",
  "Shaitan",
  "Senapati",
  "Sair",
  "Hairan",
  "Kavlnaen",
  "Kaid",
  "Khair",
  "Jarnail",
  "Jaikara",
  "Tair",
  "Nirvair",
  "Nain",
  "Baith",
  "Bhen",
  "Bhairav",
  "Madhurbhen",
  "Maidan",
  "Rain",
  "Vairag",
  "Aitvar",
  "Ailan",
  "Sweater",
];

final List<String> HorhaWords = [
  "ਸੋਚ",
  "ਸੋਮਵਾਰ",
  "ਸ਼ੋਰ",
  "ਕਮਜ਼ੋਰ",
  "ਕਰੋਧ",
  "ਕਾਰੋਬਾਰ",
  "ਕੋਇਲ",
  "ਕੋਸ਼ਿਸ਼",
  "ਗੋਦਾਵਰੀ",
  "ਚਕੋਰ",
  "ਚੋਰ",
  "ਜੋਬਨ",
  "ਜੋਰ",
  "ਜੋਰਾਵਰ",
  "ਢੋਲ",
  "ਬੋਲ",
  "ਭਰੋਸਾ",
  "ਮਨੋਬਲ",
  "ਮੋਨ",
  "ਮੋਰਚਾ",
  "ਮੋੜ",
  "ਅਮੋਲਕ",
  "ਸਰੋਵਰ",
  "ਸਲੋਕ",
];
final List<String> HorhaPronunciations = [
  "Soch",
  "Somvar",
  "Shor",
  "Kamzor",
  "Krodh",
  "Karobar",
  "Koil",
  "Koshish",
  "Godavari",
  "Chakor",
  "Chor",
  "Joban",
  "Jor",
  "Joravar",
  "Dhol",
  "Bol",
  "Bharosa",
  "Manobal",
  "Mon",
  "Morcha",
  "Mor",
  "Amolak",
  "Sarovar",
  "Slok",
];

final List<String> KnaurhaWords = [
  "ਚੌਰ",
  "ਚੌਰਾਹਾ",
  "ਤੌਲੀਆ",
  "ਧੌਣ",
  "ਨੌ ਬਰ ਨੌ",
  "ਨੌਕਰ",
  "ਨੌਜਵਾਨ",
  "ਪਕੌੜੇ",
  "ਪੌਣ",
  "ਪੌਦਾ",
  "ਫੌਜ",
  "ਬਖਤੌਰ",
  "ਬਲਾਚੌਰ",
  "ਮਖੌਲ",
  "ਮੌਸਮ",
  "ਮੌਜ",
  "ਸੌਦਾਗਰ",
  "ਹੌਸਲਾ",
  "ਕੌਣ",
  "ਕੌਰ",
  "ਖੌਫਨਾਕ",
  "ਚਮਕੌਰ",
  "ਚੌਂਕੀਦਾਰ",
  "ਚੌਬਾਰਾ",
];
final List<String> KnaurhaPronunciations = [
  "Chor",
  "Choraha",
  "Tolia",
  "Dhaun",
  "Nau Bar Nau",
  "Naukar",
  "Naujawan",
  "Pakore",
  "Pauṇ",
  "Pauda",
  "Fauj",
  "Bakhtaur",
  "Balachor",
  "Makhol",
  "Mausam",
  "Mauj",
  "Sodagar",
  "Hausla",
  "Kaun",
  "Kaur",
  "Khofnak",
  "Chamakor",
  "Chonkidar",
  "Chobara",
];


//Liste usate nei giochi per generare le parole
final Map<String, String> categoryPaths = {
    "AdhakWords": "assets/SUONI/ACCENTO-PESANTE(Addhak)",
    "BindiWords": "assets/SUONI/NASALE_GENERALE(Bindi)",
    "TippiWords": "assets/SUONI/NASALE-PARTICOLARE(Tippi)",
    "MuktaWords": "assets/SUONI/Mukta",
    "KannaWords": "assets/SUONI/Kanna",
    "SihariWords": "assets/SUONI/Sihari",
    "BihariWords": "assets/SUONI/Bihari",
    "OnkarhWords": "assets/SUONI/Onkarh",
    "DulenkarhWords": "assets/SUONI/Dulenkarh",
    "LavaaWords": "assets/SUONI/Lavaa",
    "DulaavaWords": "assets/SUONI/Dulaava",
    "HorhaWords": "assets/SUONI/Horha",
    "KnaurhaWords": "assets/SUONI/Knaurha",
  };
final Map<List<String>, String> wordCategories = {
      AdhakWords: "AdhakWords",
      BindiWords: "BindiWords",
      TippiWords: "TippiWords",
      MuktaWords: "MuktaWords",
      KannaWords: "KannaWords",
      SihariWords: "SihariWords",
      BihariWords: "BihariWords",
      OnkarhWords: "OnkarhWords",
      DulenkarhWords: "DulenkarhWords",
      LavaaWords: "LavaaWords",
      DulaavaWords: "DulaavaWords",
      HorhaWords: "HorhaWords",
      KnaurhaWords: "KnaurhaWords",
    };